"""create storage_items and shipping_addresses tables

Revision ID: e20c49188b23
Revises: 55bc3ace9fc6
Create Date: 2026-10-03 16:59:52.008078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20c49188b23'
down_revision: Union[str, Sequence[str], None] = '55bc3ace9fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_addresses',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('storage_items',
    sa.Column('storage_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('raffle', 'store', name='storage_source'), nullable=False),
    sa.Column('raffle_product_id', sa.Integer(), nullable=True),
    sa.Column('store_product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ready', 'requested', 'shipped', name='storage_status'), server_default='ready', nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['shipping_addresses.address_id'], ),
    sa.ForeignKeyConstraint(['raffle_product_id'], ['raffle_products.raffle_product_id'], ),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.store_product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('storage_item_id'),
    sa.UniqueConstraint('raffle_product_id')
    )
    # ### end Alembic commands ###

    # 이 마이그레이션 전에 이미 추첨이 끝난 당첨 건도 당첨자 보관함에 넣어준다
    op.execute("""
        INSERT INTO storage_items (user_id, source, raffle_product_id, quantity, status, created_at, updated_at)
        SELECT winner_user_id, 'raffle', raffle_product_id, 1, 'ready', COALESCE(drawn_at, now()), now()
        FROM raffle_products
        WHERE winner_user_id IS NOT NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_items')
    op.drop_table('shipping_addresses')
    # ### end Alembic commands ###
